### ISSUE TITLE
Dynamically load HTML contents based on translation keys

### ISSUE THREAD

**Issue by jacobandrews** [jquery-i18n-properties/jquery-i18n-properties#7] opened 2014-12-28 18:31 UTC
I didn't like the idea of having to edit the javascript every time I add a new key so I tried to come up with the following solution to dynamically load all HTML elements based on the translation key.  Here's the HTML for a complex types with parameters.

This also allows for dynamically passing the params from the HTML and not via javascript.  by using an additional ```<span class="param">``` inside the element I want to translate

**HTML**
``` 
<span translate="yes" class="msg_multi_placeholder">Welcome <span class="param">Jacob</span>.  Today is <span class="param">28-12-2014</span></span>
```

Below is the javascript I'm using for this:
**javascript**
```
function updateSelected(translationKey) {
	var params = '';
	$('.' + translationKey + ' .param').each(function(i, param) {
	    params = params + ', \'' + param.textContent + '\'';
	});
    var translationCommand = '$(\'.\'+translationKey).empty().append($.i18n.prop(translationKey'+ params + '));';
	eval(translationCommand);
}
function updateAll() {
	var keys = Object.keys(($.i18n.map));
	$.each(keys, function(i, key){
	   updateSelected(key);
	});
}
```

**messages_es.properties**
```
msg_multi_placeholder = Bienvenido <span class="param">{0}</span>. Hoy es el <span class="param">{1}</span>
```

I must admit, this is not very neat.  I would like to find a solution to make the property file a bit neater, a double placeholder for one parameter seems a bit much.

**Comment by Kasama** [comment] 2015-09-20 16:14
Here is my solution to the same problem:

```javascript
function refresh_i18n() {
    // Select every html element with the attribute 'data-i18n' and search the properties file for the value
    // Change this if you want a different attribute to be used
    $("[data-i18n]").each(function () {
        var prop = $(this).data('i18n');
        $(this).text($.i18n.prop(prop))
    });
}

// leave blank to use browser default language
function changeLanguage(lang) {
    lang = lang || ""; // if no language is set, use browser default
    $.i18n.properties({
        // change this settings as you wish
        path    : 'languages/', 
        mode    : 'both',
        language: lang,
        callback: refresh_i18n
    });
}

$(document).ready(function(){
    // Initialize with default language
    // you could read from cookies/webstorage the preferred language and put it here
    changeLanguage();

    // In this case I'm using a checkbox to select from 2 languages, change this to use a combobox if you want more versatility
    $('#languageSelector').click(function () {
        var sel = $('#languageSelector').prop('checked') ? "en" : "pt";
        changeLanguage(sel);
    });
});
```
In your HTML document:
```HTML
<h1 data-i18n="welcome_message">Text here will only be displayed if user do not run Javascript</h1>
```

In your Messages.properties:
```
welcome_message = This will be shown by default
```
Add other languages as you wish

Hope to have helped

**Comment by adrianfish** [comment] 2016-01-13 17:08
I'm closing this as it is not a bug. There are some good ideas here and they will remain on the issue, even though it will be closed. Maybe we should start a Google group or something, where stuff like this can be discussed more easily.

**Closed by adrianfish** 2016-01-13 17:08 UTC
